apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: opsguard
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: opsguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: jeffoisrael/opsguard-db:latest
          env:
            - name: POSTGRES_DB
              value: opsguard
            - name: POSTGRES_USER
              value: opsguard
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opsguard-secrets
                  key: POSTGRES_PASS
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "opsguard", "-d", "opsguard"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: opsguard
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
